export const directors:string = "http://localhost:3000/api/directors"
export const groups:string = "http://localhost:3000/api/groups"
export const institutions:string = "http://localhost:3000/api/institutions"
export const students:string = "http://localhost:3000/api/students"
export const timtables:string = "http://localhost:3000/api/timetable"
export const tutors:string = "http://localhost:3000/api/tutors"

export const checkDirectors:string = "http://localhost:3000/api/checkdirectors"
export const checkTutors:string = "http://localhost:3000/api/checktutors"
export const checkStudents:string = "http://localhost:3000/api/checkstudents"