export const directors:string = "http://localhost:3000/api/directors"
export const groups:string = "http://localhost:3000/api/groups"
export const institutions:string = "http://localhost:3000/api/institutions"
export const students:string = "http://localhost:3000/api/students"
export const timtables:string = "http://localhost:3000/api/timetable"
export const tutors:string = "http://localhost:3000/api/tutors"

export const monday:string = "http://localhost:3000/api/monday"
export const tuesday:string = "http://localhost:3000/api/tuesday"
export const wednesday:string = "http://localhost:3000/api/wednesday"
export const thursday:string = "http://localhost:3000/api/thursday"
export const friday:string = "http://localhost:3000/api/friday"
export const saturday:string = "http://localhost:3000/api/saturday"