export const directors:string = "http://localhost:3000/api/directors"
export const groups:string = "http://localhost:3000/api/groups"
export const institutions:string = "http://localhost:3000/api/institutions"
export const students:string = "http://localhost:3000/api/students"
export const timtables:string = "http://localhost:3000/api/timetable"
export const tutors:string = "http://localhost:3000/api/tutors"

export const loginDirectors:string = "http://localhost:3000/api/logindirectors"
export const loginTutors:string = "http://localhost:3000/api/logintutors"
export const loginStudents:string = "http://localhost:3000/api/loginstudents"